### ISSUE TITLE
How to improve the speed of streaming implementation？

### ISSUE THREAD

**Issue by lingdhox** [facebookresearch/denoiser#104]
For the same audio data, the processing speed of DemucsStreamer is much slower. 
As the DemucsStreamer needs to handle a lot of redundant data for resampling.
Is it possible to avoid processing redundant data?

**Comment by adefossez** [comment]
there is no redundant processing in `DemucsStreamer`, it does exactly the same computation as the non streaming version. the resampling is only a very minor part of the processing and the smaller buffer is there only to avoid edge artifacts.

**Comment by lingdhox** [comment]
Indeed, dividing data into multiple processes is much slower than one-time processing

For 10 seconds of audio data, torch Size([1, 1, 160000]), pretrained dns48 model.
Demucs cost: 750ms
DemucsStreamer with num_frames=1 cost: 3800ms RTF:0.38
DemucsStreamer with num_frames=2 cost: 2400ms RTF:0.24
Increasing num_frames, the DemucsStreamer  will be close to the demucs

**Comment by adefossez** [comment]
The slower performance is likely due to cache behavior in the CPU. When processing a large audio extract at once, model weights are loaded  into cache and used for a large number of samples. But when processing very small chunks, model weights for each layer are loaded sequentially into the cache but only used for a very small extract, before being flushed out of the cache by the next layers than needs to be computed. But the actual amount of computation is exactly the same.
