### ISSUE TITLE
what is the purpose of "first" in _separate_frame function

### ISSUE THREAD

**Issue by flytair** [facebookresearch/denoiser#26]
hi,
it is an amazing project, and thank you for the awesome work!

when i tried to understand _separate_frame function:
https://github.com/facebookresearch/denoiser/blob/84a5c0032d118b619a59b7502a1ffbdddef43fd7/denoiser/demucs.py#L345
	
specifically this line, why need this operation?
https://github.com/facebookresearch/denoiser/blob/84a5c0032d118b619a59b7502a1ffbdddef43fd7/denoiser/demucs.py#L373

thanks a lot again!

**Comment by adefossez** [comment]
One frame is 36ms of audio, but the stride between frames is 16ms, so that there is 20ms of overlap. A naive implementation would recompute the convolutions for this 20ms in common. Instead here, we only compute the convolutions for the new part of the audio and merge the two (cache from the end of the previous frame + newly computed).
`first` means is it the first frame of audio we are processing, in which case there is no cache from the previous frame and we need to compute the convolution over the entire input.

**Comment by flytair** [comment]
thanks for your quick response!
got it. 
i will close this issue.

**Comment by adefossez** [comment]
Overlaps improve the quality of the signal, I can't give a specific reason but it is often the case with convolutions. If you take spectrogram models, the STFT overlaps by 50 to 75% usually, so that the prediction for each time step is going to be averaged from the prediction of multiple frames.

**Comment by flytair** [comment]
i got it, thanks for your response! i will close this issue.
