### ISSUE TITLE
Usage example denoiser

### ISSUE THREAD

**Issue by Eppi199** [facebookresearch/denoiser#56]
Hi, I apologize for the stupid question, but what commands need to be run to remove noise from wav file (indicating the path to it)?

**Comment by youssefavx** [comment]
This is described here: https://github.com/facebookresearch/denoiser#4-denoising

```
python -m denoiser.enhance --model_path=<path to the model> --noisy_dir=<path to the dir with the noisy files> --out_dir=<path to store enhanced files>
```

If you want to use a pre-trained model, you replace --model_path with:

```
python -m denoiser.enhance --dns64 --noisy_dir=<path to the dir with the noisy files> --out_dir=<path to store enhanced files>

```
(You can use either dns64, dns48, or master64)

You would do this without the brackets <> for every directory.

I would recommend starting with a small file like 1 minute or less, and also make sure it's 16kHz since these models are trained on that.
