### ISSUE TITLE
FineTuning on custom dataset using pre-trained models

### ISSUE THREAD

**Issue by archiki** [facebookresearch/denoiser#7]
Hi!
The pre-trained model is performing really well on my dataset. I wanted to finetune this model, that is, master64 (trained on Valentini and DNS datasets), on my dataset and then check the results. Could you let me know how I can do that?
On a tangential note, in the config files, there is a parameter called ```matching``` which is set to sort. If I have understood correctly, as long as clean and noisy files are named similarly so that they have the same order on sort, the matching is successul, am I correct?
Thanks in advance for the clarification!

**Comment by adefossez** [comment]
Hello @archiki, in order to fine tune on your dataset, first make sure all the audio is in wav format at 16kHz and mono.
Then look at https://github.com/facebookresearch/denoiser#setting-up-a-new-dataset (and look at `./make_debug.sh` and `config/dset/debug.yaml` to see how to adapt it).

Then, to start from an existing pre-trained model you can do
```bash
./train.py continue_pretrained=master64
```

Indeed, the `matching` config decides how to match noisy and clean samples. `sort` means both list of files will be sorted and matched in order, like you said. This is not valid for some datasets like dns, in which case we use a custom matching function.

**Comment by archiki** [comment]
Thanks @adefossez ! Just an addition the `debug.yaml` one has to change the `hidden-size` in the file `config.yaml`. After that, the training starts without any issues.
